### ISSUE TITLE
Not Compatible with Mac OS

### ISSUE THREAD

**Issue by TheEzeJC** [SteveKunG/YouTubeChat#1]
This mod is not compatible with Mac OS. The mod adds files as if it were in Windows.

**Comment by SteveKunG** [comment]
Why not? Did you have crash log?

**Comment by TheEzeJC** [comment]
I don't have a changelog. Just an image.
![2017-12-26_22 10 33](https://user-images.githubusercontent.com/10842053/34371397-001f2c2e-ea8a-11e7-84c3-388523936e86.png)

**Comment by TheEzeJC** [comment]
I believe I get this error because the directory is set as if I am using Windows. I am using MacOS.

**Comment by SteveKunG** [comment]
Yes, I only develop on Windows. I will try to fix it if I got Mac.

**Comment by TheEzeJC** [comment]
If you want, I can attempt to fix. I will just need to know where to start. Such as where do I have to go to change the file directory.

**Comment by SteveKunG** [comment]
https://github.com/SteveKunG/YouTubeChat/blob/master/src/main/java/com/google/youtube/gaming/chat/Authentication.java#L88

**Comment by SteveKunG** [comment]
Please try with dev build (1.12.2) : https://drive.google.com/file/d/1sZargDVQNRTO_BLgw9fAAjEgLaz9SB_r/view?usp=sharing

**Comment by SteveKunG** [comment]
OK, This should be fixed in 1.3.4.

https://github.com/SteveKunG/YouTubeChat/releases/tag/1.3.4

Please reopen this if you still got an issue, Thanks!

**Comment by TheEzeJC** [comment]
You fixed it! Nice!
I was still learning to how to edit the mod xP
Ima still continue to learn API's so I could probably help in the future.

**Comment by SteveKunG** [comment]
This is very difficult if you want to edit the mod but yeah, I appreciate your help. :)
